Hayvan Barınağı/Controllers/UserHayvanController.cs
using Hayvan_Barınağı.Data;
using Hayvan_Barınağı.Models.Hayvan;
using Hayvan_Barınağı.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace Hayvan_Barınağı.Controllers
{
    [Authorize(Roles = "User")]

    public class UserHayvanController : Controller
    { 
        private BarinakDbContext _barinakDbContext;
        public UserHayvanController(BarinakDbContext barinakDbContext)
        {
            _barinakDbContext = barinakDbContext;
        }


        [HttpGet]
        public async Task<IActionResult> Ekle()
        {
            var turler = await _barinakDbContext.Turler.ToListAsync();
            var cinsler = await _barinakDbContext.Cinsler.ToListAsync();

            var model = new HayvanEkleRequest
            {
                Turler = turler.Select(x => new SelectListItem { Text = x.TurAdi, Value = x.TurId.ToString() }),
                Cinsler = cinsler.Select(x => new SelectListItem { Text = x.CinsAdi, Value = x.CinsId.ToString() })
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Ekle(HayvanEkleRequest RequestModel)
        {

            DateTime currentDateTime = DateTime.Now;

            //Map Request Model to actual Model
            var hayvan = new Hayvan
            {
                HayvanAdi = RequestModel.HayvanAdi,
                Yas = RequestModel.Yas,
                Cinsiyet = RequestModel.Cinsiyet,
                Sahiplenildi = RequestModel.Sahiplenildi,
                Aciklama = RequestModel.Aciklama,
                EklenmeTarihi = currentDateTime,
                Cins = await _barinakDbContext.Cinsler.FindAsync(new Guid(RequestModel.SecilenCins)),
                Tur = await _barinakDbContext.Turler.FindAsync(new Guid(RequestModel.SecilenTur)),
                fotografURL = RequestModel.fotografURL

            };

            await _barinakDbContext.Hayvanlar.AddAsync(hayvan);
            await _barinakDbContext.SaveChangesAsync();

            return RedirectToAction("Goster");
        }

        [HttpGet]
        [ActionName("Goster")]
        public async Task<IActionResult> Goster()
        {

            var list = await _barinakDbContext.Hayvanlar.ToListAsync();

            return View(list);
        }

        [HttpGet]
        [ActionName("Sahiplen")]

        public async Task<IActionResult> Sahiplen(Guid HayvanId)
        {

            var eskiHayvan = await _barinakDbContext.Hayvanlar.FindAsync(HayvanId);

            if (eskiHayvan != null)
            {
                eskiHayvan.SahiplenmeDurumu = 1;
                await _barinakDbContext.SaveChangesAsync();
                return RedirectToAction("Goster");

            }

            return RedirectToAction("Goster");

        }
    }
}

Hayvan Barınağı/Views/UserHayvan/Ekle.cshtml
@model Hayvan_Barınağı.Models.ViewModels.HayvanEkleRequest
@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>
            Yeni Hayvan Ekle - Kullanıcı
        </h1>

    </div>
</div>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">
                Hayvan Adı
            </label>
            <input type="text" class="form-control" id="HayvanAdi" asp-for="HayvanAdi" />

            <div class="mb-3">
                <label class="form-label">Tür</label>
                <select class="form-select"
                        asp-items="@Model.Turler"
                        asp-for="SecilenTur">
                </select>
            </div>


            <div class="mb-3">
                <label class="form-label">Cins</label>
                <select class="form-select"
                        asp-items="@Model.Cinsler"
                        asp-for="SecilenCins">
                </select>
            </div>

            <label class="form-label">
                Yaş
            </label>
            <input type="number" class="form-control" id="HayvanYas" asp-for="Yas" />
            <br />
            <label class="form-label">
                Cinsiyet
            </label>
            <br />
            <select name="Cinsiyet" id="Cinsiyet">
                <option value="Dişi">Dişi</option>
                <option value="Erkek">Erkek</option>
            </select>
            <br />


            <label class="form-label">
                Açıklama
            </label>

            <textarea class="form-control" id="Aciklama" asp-for="Aciklama"> </textarea>

            <br />
            <label class="form-label">
             Fotoğraf URL
            </label>

            <textarea class="form-control" id="fotografURL" asp-for="fotografURL"> </textarea>

        </div>

        <button type="submit" class=" btn btn-dark"> Ekle </button>
    </form>
</div>

Hayvan Barınağı/Views/UserHayvan/Goster.cshtml
@model List<Hayvan_Barınağı.Models.Hayvan.Hayvan>

@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>
            Hayvanları Göster - Kullanıcı
        </h1>

    </div>
</div>


<div class="container py-5">

    @{
        if (Model != null && Model.Any())
        {
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Hayvan Türü</th>
                        <th scope="col">Hayvan Cinsi</th>
                        <th scope="col">Hayvan Adı</th>
                        <th scope="col">Hayvan Yaşı</th>
                        <th scope="col">Sahiplenildi mi?</th>
                        <th scope="col"> Sahiplen </th>

                        <th scope="col"> </th>

                    </tr>
                </thead>

                <tbody>
                    @foreach (var Hayvan in Model)
                    {
                        <tr>
                            <td>@Hayvan.HayvanId</td>
                            <td>@Hayvan.TurAdi</td>
                            <td>@Hayvan.CinsAdi</td>
                            <td>@Hayvan.HayvanAdi</td>
                            <td>@Hayvan.Yas</td>
                            <td>
                                @if (@Hayvan.Sahiplenildi)
                                {
                                    <p>Evet</p>
                                }
                                else
                                {
                                    <p>Hayır</p>
                                }
                            </td>
                            <td>
                                @if (Hayvan.SahiplenmeDurumu != 1)
                                {
                                    <a class="btn btn-info"
                                       asp-area=""
                                       asp-controller="UserHayvan"
                                       asp-action="Sahiplen"
                                       asp-route-HayvanId="@Hayvan.HayvanId">
                                       Sahiplen
                                    </a>} else 
                                    {
                                        <p> Aktif Sahiplenme İsteği Var.</p>
                                    }
                                    </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p> Kayıtlı Hayvan bulunamadı</p>
        }
    }

</div>

Hayvan Barınağı/Views/UserHayvan/HayvanlariGoster.cshtml
@model List<Hayvan_Barınağı.Models.Hayvan.Hayvan>

@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>
            Hayvanları Göster - Kullanıcı
        </h1>

    </div>
</div>


<div class="container py-5">

    @{
        if (Model != null && Model.Any())
        {
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Hayvan Türü</th>
                        <th scope="col">Hayvan Cinsi</th>
                        <th scope="col">Hayvan Adı</th>
                        <th scope="col">Hayvan Yaşı</th>
                        <th scope="col">Sahiplenildi mi?</th>

                        <th scope="col"> </th>

                    </tr>
                </thead>

                <tbody>
                    @foreach (var Hayvan in Model)
                    {
                        <tr>
                            <td>@Hayvan.HayvanId</td>
                            <td>@Hayvan.TurAdi</td>
                            <td>@Hayvan.CinsAdi</td>
                            <td>@Hayvan.HayvanAdi</td>
                            <td>@Hayvan.Yas</td>
                            <td>@if (@Hayvan.Sahiplenildi)
                                {
                                    <p>Evet</p>
                                }
                                else
                                {
                                    <p>Hayır</p>
                                }</td>

                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p> Kayıtlı Hayvan bulunamadı</p>
        }
    }

</div>